[package]
name = "rapira_core"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true


[workspace]
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1"
log = { version = "0.4", features = ["std"] }
php_sys = { path = "crates/php_sys" }
extension_host = { path = "crates/extension_host" }
tokio = { version = "1", features = ["sync"] }
bytes = "1"

[workspace.package]
rust-version = "1.96.1"

[workspace.lints.clippy]
all = "warn"

[dependencies]
anyhow = { workspace = true }
extension_host = { workspace = true }
log = { workspace = true, features = ["std"] }
php_sys = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
