[package]
name = "integration-tests"
version = "0.1.0"
edition = "2024"
publish = false
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
php_sys = { path = "../php_sys" }
tokio = { version = "1", features = ["sync"] }
log = "0.4"

[dev-dependencies]
anyhow = "1"
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }
